# The blog we want to post to.
blog: api-demo
# the tags we want to post with.
tags:
  - twitter
  - testing
  - just funning ya
search_term: '#garageofidiots'
# How the last seen tweet ID will be saved between
# runs of the process.
cookie_store: txt
